### ISSUE TITLE
Add page about Predictive Modeling BookClub

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/waldronlab.github.io#4]
Please include link to sign up spreadsheet and textbook

**Comment by schifferl** [comment]
Will have it done shortly

**Comment by LiNk-NY** [comment]
I don't see the page or the commit.

**Comment by schifferl** [comment]
Not quite done yet, but closed the issue. Will commit in the next few minutes.

**Comment by LiNk-NY** [comment]
You can close it as you commit by including something like "closes #4" in the commit message.

**Comment by schifferl** [comment]
see 6a0f8a3 for the page I have added
